from dto.process import EnveloppeParamsDto, PotentielParamsDto
def register_enveloppe(params: EnveloppeParamsDto):
    ...
def register_potentiel(params: PotentielParamsDto):
    ...
def envelop_creation(id: str):
    ...
def potentiel_calcul(id: str):
    ...